import "@/styles/globals.css";

import type { Metadata } from "next";
import { Toaster } from "sonner";

import { TailwindIndicator } from "@/components/tailwind-indicator";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import { ConvexClientProvider } from "@/components/providers/convex-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.className
        )}
      >
        <ConvexClientProvider>
          <Toaster position="bottom-right" />
          {children}
          <TailwindIndicator />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
